### ISSUE TITLE
Problem with opening .conf files

### ISSUE THREAD

**Issue by Seb-lef** [gobo-ws/ola-trigger-hue-dmx#2]
Hello, sorry i'm a noob and i don't know why each time i try to launch for example : 
ola-trigger philips_hue_osram_lightify.conf
in a LXTerminal, i have this message :
tools/ola_trigger/ola-trigger.cpp:191: File philips_hue_osram_lightify.conf cannot be opened.

The file is in the correct directory...so why?

Thanks for your help

**Comment by gobo-ws** [comment]
Hi, I only got that error message when the file is missing. 
Are you sure that you run ola_trigger from the directory where the config file is stored and that the name on the config file is correct?

**Comment by Seb-lef** [comment]
Thanks Johan!
ok i was not in the correct directory when i launched the cmd... so now, i don't have any error but nothing happen in the terminal, i have only a blank square and nothing happen when i send dmx from my desk...

**Comment by gobo-ws** [comment]
Ah I see! What universe do you use? The default is 0 if you don't specify anything else.
`ola_trigger -u1 philips_hue_osram_lightify.conf`
if you want to run it on universe 1 for instance.

**Comment by Seb-lef** [comment]
A huge thanks! it was that!
So now, i have to work on how launch video from omxplayer with that type of links...
For a noob, it's a bit difficult but i try to learn slowly..
thanks a lot
Seb

**Comment by gobo-ws** [comment]
Your welcome! 
Hopefully you can find some more help on the following pages:
https://www.openlighting.org/ola/advanced-topics/ola-dmx-trigger/
https://wiki.openlighting.org/index.php?title=Raspberry_Pi_Media_Player
https://groups.google.com/forum/#!topic/open-lighting/hjZZ1lJ6xIk
https://github.com/OpenLightingProject/ola/blob/master/tools/ola_trigger/test_file.conf

Good luck!
